//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eindstagesets
    {
        public int Stage_Id { get; set; }
        public Nullable<int> TweedeLezer { get; set; }
    
        public virtual docentsets docentsets { get; set; }
        public virtual stagesets stagesets { get; set; }
    }
}
