//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opleidingsets
    {
        public opleidingsets()
        {
            this.studentsets = new HashSet<studentsets>();
            this.docentsets = new HashSet<docentsets>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int acedemieId { get; set; }
    
        public virtual academiesets academiesets { get; set; }
        public virtual ICollection<studentsets> studentsets { get; set; }
        public virtual ICollection<docentsets> docentsets { get; set; }
    }
}
