//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acedemieset
    {
        public acedemieset()
        {
            this.opleidingsets = new HashSet<opleidingset>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<opleidingset> opleidingsets { get; set; }
    }
}
