//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adressets
    {
        public adressets()
        {
            this.bedrijfsets = new HashSet<bedrijfsets>();
            this.docentsets = new HashSet<docentsets>();
        }
    
        public int Id { get; set; }
        public string Plaats { get; set; }
        public string Straat { get; set; }
        public string Huisnummer { get; set; }
        public string Postcode { get; set; }
    
        public virtual ICollection<bedrijfsets> bedrijfsets { get; set; }
        public virtual ICollection<docentsets> docentsets { get; set; }
    }
}
