//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class algemeenset
    {
        public algemeenset()
        {
            this.docentsets = new HashSet<docentset>();
        }
    
        public int Id { get; set; }
        public String Jaargang { get; set; }
        public String Werk_Uren { get; set; }
        public String Blokken { get; set; }
    
        public virtual ICollection<docentset> docentsets { get; set; }
    }
}
