//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Algemeen
    {
        public Algemeen()
        {
            this.Docent = new HashSet<Docent>();
        }
    
        public int Id { get; set; }
        public System.DateTime Jaargang { get; set; }
        public short Werk_Uren { get; set; }
        public short Blokken { get; set; }
    
        public virtual ICollection<Docent> Docent { get; set; }
    }
}
