//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedrijfsetset
    {
        public bedrijfsetset()
        {
            this.adressets = new HashSet<adresset>();
            this.bedrijfenbegeleidersets = new HashSet<bedrijfenbegeleiderset>();
        }
    
        public int Bedrijfs_Id { get; set; }
        public string Naam { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<adresset> adressets { get; set; }
        public virtual ICollection<bedrijfenbegeleiderset> bedrijfenbegeleidersets { get; set; }
    }
}
