//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedrijfsbegeleiderset
    {
        public bedrijfsbegeleiderset()
        {
            this.stagesets = new HashSet<stageset>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Functie { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public string Email { get; set; }
        public string Opleidingsniveau { get; set; }
        public string Minimale_begeleidingstijd_gegarandeerd { get; set; }
        public int BedrijfBedrijfs_Id { get; set; }
    
        public virtual bedrijfset bedrijfset { get; set; }
        public virtual ICollection<stageset> stagesets { get; set; }
    }
}
