//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedrijfset
    {
        public bedrijfset()
        {
            this.bedrijfsbegeleidersets = new HashSet<bedrijfsbegeleiderset>();
            this.stagesets = new HashSet<stageset>();
        }
    
        public int Bedrijfs_Id { get; set; }
        public string Naam { get; set; }
        public string Straatnaam_en_nummer { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<bedrijfsbegeleiderset> bedrijfsbegeleidersets { get; set; }
        public virtual ICollection<stageset> stagesets { get; set; }
    }
}
