//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedrijfenbegeleiderset
    {
        public bedrijfenbegeleiderset()
        {
            this.stagesets = new HashSet<stageset>();
        }
    
        public int Id { get; set; }
        public int bedrijfsbegeleidersetId { get; set; }
        public int bedrijfsetBedrijfs_Id { get; set; }
    
        public virtual bedrijfsbegeleiderset bedrijfsbegeleiderset { get; set; }
        public virtual ICollection<stageset> stagesets { get; set; }
        public virtual bedrijfset bedrijfset { get; set; }
    }
}
