//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docentsets
    {
        public docentsets()
        {
            this.opleidingsets = new HashSet<opleidingsets>();
            this.tool_vaardigheidset = new HashSet<tool_vaardigheidset>();
        }
    
        public int Leraar_Id { get; set; }
        public Nullable<short> DBU1 { get; set; }
        public Nullable<short> DBU2 { get; set; }
        public Nullable<short> DBU3 { get; set; }
        public Nullable<short> DBU4 { get; set; }
        public int stagesetStage_Id { get; set; }
        public int algemeensetId { get; set; }
        public int Id { get; set; }
        public int adresset_Id { get; set; }
        public int webkeysets_Id { get; set; }
    
        public virtual adressets adressets { get; set; }
        public virtual algemeensets algemeensets { get; set; }
        public virtual persoonsets persoonsets { get; set; }
        public virtual stagesets stagesets { get; set; }
        public virtual webkeysets webkeysets { get; set; }
        public virtual ICollection<opleidingsets> opleidingsets { get; set; }
        public virtual ICollection<tool_vaardigheidset> tool_vaardigheidset { get; set; }
    }
}
