//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docentset
    {
        public docentset()
        {
            this.stagesets = new HashSet<stageset>();
        }
    
        public int Leraar_Id { get; set; }
        public string Naam { get; set; }
        public string Straatnaam_en_nr { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public string Telefoonnummer { get; set; }
        public int Algemene_InformatieId { get; set; }
        public Nullable<short> DBU1 { get; set; }
        public Nullable<short> DBU2 { get; set; }
        public Nullable<short> DBU3 { get; set; }
        public Nullable<short> DBU4 { get; set; }
        public int AlgemeenId { get; set; }
    
        public virtual algemeenset algemeenset { get; set; }
        public virtual ICollection<stageset> stagesets { get; set; }
    }
}
