//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kennisgebiedset
    {
        public kennisgebiedset()
        {
            this.docentsets = new HashSet<docentsets>();
            this.stagesets = new HashSet<stagesets>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<docentsets> docentsets { get; set; }
        public virtual ICollection<stagesets> stagesets { get; set; }
    }
}
