//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student> StudentSet { get; set; }
        public DbSet<Docent> DocentSet { get; set; }
        public DbSet<Bedrijfsbegeleider> BedrijfsbegeleiderSet { get; set; }
        public DbSet<Bedrijf> BedrijfSet { get; set; }
        public DbSet<Stage> StageSet { get; set; }
        public DbSet<Algemeen> AlgemeenSet { get; set; }
    }
}
