//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opleidingset
    {
        public opleidingset()
        {
            this.persoonset_studentset = new HashSet<persoonset_studentset>();
            this.persoonset_docentset = new HashSet<persoonset_docentset>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int acedemieId { get; set; }
    
        public virtual acedemieset acedemieset { get; set; }
        public virtual ICollection<persoonset_studentset> persoonset_studentset { get; set; }
        public virtual ICollection<persoonset_docentset> persoonset_docentset { get; set; }
    }
}
