//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persoonset_bedrijfsbegeleiderset
    {
        public persoonset_bedrijfsbegeleiderset()
        {
            this.bedrijfenbegeleidersets = new HashSet<bedrijfenbegeleiderset>();
        }
    
        public string Functie { get; set; }
        public string Opleidingsniveau { get; set; }
        public Nullable<bool> Minimale_begeleidingstijd_gegarandeerd { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<bedrijfenbegeleiderset> bedrijfenbegeleidersets { get; set; }
        public virtual persoonset persoonset { get; set; }
    }
}
