//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageset
    {
        public stageset()
        {
            this.kennisgebiedsets = new HashSet<kennisgebiedset>();
        }
    
        public int Stage_Id { get; set; }
        public Nullable<System.DateTime> Start_datum { get; set; }
        public Nullable<System.DateTime> Eind_datum { get; set; }
        public string Stageopdracht_omschijving { get; set; }
        public Nullable<int> Bedrijfsbegeleider_id { get; set; }
        public int studentset1_Id { get; set; }
        public Nullable<int> studentset2_Id { get; set; }
        public Nullable<int> docentset_Id { get; set; }
    
        public virtual bedrijfsbegeleiderset bedrijfsbegeleiderset { get; set; }
        public virtual docentset docentset { get; set; }
        public virtual eindstageset eindstageset { get; set; }
        public virtual studentset studentset { get; set; }
        public virtual studentset studentset1 { get; set; }
        public virtual ICollection<kennisgebiedset> kennisgebiedsets { get; set; }
    }
}
