//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageset
    {
        public Nullable<System.DateTime> Start_datum { get; set; }
        public Nullable<System.DateTime> Eind_datum { get; set; }
        public string Stageopdracht_omschijving { get; set; }
        public string Tools_en_Vaardigheden { get; set; }
        public string Risico { get; set; }
        public int StudentStudentnummer { get; set; }
        public int LeraarLeraar_Id { get; set; }
        public int BedrijfBedrijfs_Id { get; set; }
        public int BedrijfsbegeleiderId { get; set; }
        public int Stage_Id { get; set; }
    
        public virtual bedrijfsbegeleiderset bedrijfsbegeleiderset { get; set; }
        public virtual bedrijfset bedrijfset { get; set; }
        public virtual docentset docentset { get; set; }
        public virtual studentset studentset { get; set; }
    }
}
