//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stagesets
    {
        public stagesets()
        {
            this.bedrijfsbegeleidersets = new HashSet<bedrijfsbegeleidersets>();
            this.docentsets = new HashSet<docentsets>();
            this.tool_vaardigheidset = new HashSet<tool_vaardigheidset>();
        }
    
        public int Stage_Id { get; set; }
        public Nullable<System.DateTime> Start_datum { get; set; }
        public Nullable<System.DateTime> Eind_datum { get; set; }
        public string Stageopdracht_omschijving { get; set; }
        public int bedrijfEnBegeleiderId { get; set; }
        public int studentset_Id { get; set; }
    
        public virtual ICollection<bedrijfsbegeleidersets> bedrijfsbegeleidersets { get; set; }
        public virtual ICollection<docentsets> docentsets { get; set; }
        public virtual studentsets studentsets { get; set; }
        public virtual ICollection<tool_vaardigheidset> tool_vaardigheidset { get; set; }
    }
}
