//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class stagemanagerEntities : DbContext
    {
        public stagemanagerEntities()
            : base("name=stagemanagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acedemieset> acedemiesets { get; set; }
        public DbSet<adresset> adressets { get; set; }
        public DbSet<algemeenset> algemeensets { get; set; }
        public DbSet<bedrijfsbegeleiderset> bedrijfsbegeleidersets { get; set; }
        public DbSet<bedrijfset> bedrijfsets { get; set; }
        public DbSet<docentset> docentsets { get; set; }
        public DbSet<opleidingset> opleidingsets { get; set; }
        public DbSet<persoonset> persoonsets { get; set; }
        public DbSet<stageset> stagesets { get; set; }
        public DbSet<studentset> studentsets { get; set; }
        public DbSet<tool_vaardigheidset> tool_vaardigheidset { get; set; }
        public DbSet<webkeyset> webkeysets { get; set; }
    
        public virtual ObjectResult<algemeenset> SearchAlgemeenSet(string in_searchQuery)
        {
            var in_searchQueryParameter = in_searchQuery != null ?
                new ObjectParameter("in_searchQuery", in_searchQuery) :
                new ObjectParameter("in_searchQuery", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<algemeenset>("SearchAlgemeenSet", in_searchQueryParameter);
        }
    
        public virtual ObjectResult<algemeenset> SearchAlgemeenSet(string in_searchQuery, MergeOption mergeOption)
        {
            var in_searchQueryParameter = in_searchQuery != null ?
                new ObjectParameter("in_searchQuery", in_searchQuery) :
                new ObjectParameter("in_searchQuery", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<algemeenset>("SearchAlgemeenSet", mergeOption, in_searchQueryParameter);
        }
    }
}
