//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stagemanagerEntities : DbContext
    {
        public stagemanagerEntities()
            : base("name=stagemanagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<algemeenset> algemeensets { get; set; }
        public DbSet<bedrijfsbegeleiderset> bedrijfsbegeleidersets { get; set; }
        public DbSet<bedrijfset> bedrijfsets { get; set; }
        public DbSet<docentset> docentsets { get; set; }
        public DbSet<stageset> stagesets { get; set; }
        public DbSet<studentset> studentsets { get; set; }
    }
}
