//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageset
    {
        public stageset()
        {
            this.persoonset_docentset = new HashSet<persoonset_docentset>();
            this.tool_vaardigheidset = new HashSet<tool_vaardigheidset>();
        }
    
        public int Stage_Id { get; set; }
        public Nullable<System.DateTime> Start_datum { get; set; }
        public Nullable<System.DateTime> Eind_datum { get; set; }
        public string Stageopdracht_omschijving { get; set; }
        public int bedrijfEnBegeleiderId { get; set; }
        public int studentset_Id { get; set; }
    
        public virtual bedrijfenbegeleiderset bedrijfenbegeleiderset { get; set; }
        public virtual ICollection<persoonset_docentset> persoonset_docentset { get; set; }
        public virtual persoonset_studentset persoonset_studentset { get; set; }
        public virtual ICollection<tool_vaardigheidset> tool_vaardigheidset { get; set; }
    }
}
