//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class stagemanagerEntities : DbContext
    {
        public stagemanagerEntities()
            : base("name=stagemanagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<academiesets> academiesets { get; set; }
        public DbSet<adressets> adressets { get; set; }
        public DbSet<algemeensets> algemeensets { get; set; }
        public DbSet<bedrijfsbegeleidersets> bedrijfsbegeleidersets { get; set; }
        public DbSet<bedrijfsets> bedrijfsets { get; set; }
        public DbSet<coordinator> coordinator { get; set; }
        public DbSet<docentsets> docentsets { get; set; }
        public DbSet<eindstagesets> eindstagesets { get; set; }
        public DbSet<kennisgebiedset> kennisgebiedset { get; set; }
        public DbSet<opleidingsets> opleidingsets { get; set; }
        public DbSet<persoonsets> persoonsets { get; set; }
        public DbSet<stagesets> stagesets { get; set; }
        public DbSet<studentsets> studentsets { get; set; }
        public DbSet<tempemailsets> tempemailsets { get; set; }
        public DbSet<webkeysets> webkeysets { get; set; }
    
        public virtual ObjectResult<algemeensets> SearchAlgemeenSet(string in_searchQuery)
        {
            var in_searchQueryParameter = in_searchQuery != null ?
                new ObjectParameter("in_searchQuery", in_searchQuery) :
                new ObjectParameter("in_searchQuery", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<algemeensets>("SearchAlgemeenSet", in_searchQueryParameter);
        }
    
        public virtual ObjectResult<algemeensets> SearchAlgemeenSet(string in_searchQuery, MergeOption mergeOption)
        {
            var in_searchQueryParameter = in_searchQuery != null ?
                new ObjectParameter("in_searchQuery", in_searchQuery) :
                new ObjectParameter("in_searchQuery", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<algemeensets>("SearchAlgemeenSet", mergeOption, in_searchQueryParameter);
        }
    
        public virtual ObjectResult<docentsets> SearchDocentSet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docentsets>("SearchDocentSet");
        }
    
        public virtual ObjectResult<docentsets> SearchDocentSet(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docentsets>("SearchDocentSet", mergeOption);
        }
    
        public virtual ObjectResult<studentsets> SearchStudentSet(string in_SearchString)
        {
            var in_SearchStringParameter = in_SearchString != null ?
                new ObjectParameter("in_SearchString", in_SearchString) :
                new ObjectParameter("in_SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<studentsets>("SearchStudentSet", in_SearchStringParameter);
        }
    
        public virtual ObjectResult<studentsets> SearchStudentSet(string in_SearchString, MergeOption mergeOption)
        {
            var in_SearchStringParameter = in_SearchString != null ?
                new ObjectParameter("in_SearchString", in_SearchString) :
                new ObjectParameter("in_SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<studentsets>("SearchStudentSet", mergeOption, in_SearchStringParameter);
        }
    }
}
