//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentset
    {
        public int Studentnummer { get; set; }
        public string Name { get; set; }
        public string Straatnaam_en_nr { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public int Telefoonnummer { get; set; }
        public bool EC_norm_behaald { get; set; }
    }
}
