//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool_vaardigheidset
    {
        public tool_vaardigheidset()
        {
            this.persoonset_docentset = new HashSet<persoonset_docentset>();
            this.stagesets = new HashSet<stageset>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<persoonset_docentset> persoonset_docentset { get; set; }
        public virtual ICollection<stageset> stagesets { get; set; }
    }
}
